<?php
/**
 *

 */

// @codingStandardsIgnoreFile
/**
 * @var $block \MagentoFarsi\Mellat\Block\Info
 */
?>

<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getLastTransId() == ''): ?>
    <br /><?php echo __('No transaction ID recorded.') ?>
<?php else: ?>
    <br /><?php echo __('Mellat Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
<?php endif; ?>
